
static char* french_number[] = {
#define FRENCH_DIGIT_0 0
/*  0 */	"zéro",   			
/*  1 */	"une",
/*  2 */	"deux",
/*  3 */	"trois",
/*  4 */	"quatre",
/*  5 */	"cinq",
/*  6 */	"six",
/*  7 */	"sept",
/*  8 */	"huit",
/*  9 */	"neuf",
/* 10 */	"dix",
/* 11 */	"onze",
/* 12 */	"douze",
/* 13 */	"treize",
/* 14 */	"quatorze",
/* 15 */	"quinze",
/* 16 */	"seize",
/* 17 */	"dix-sept",
/* 18 */	"dix-huit",
/* 19 */	"dix-neuf",
/* 20 */	"vingt",
/* 21 */	"vingt et une",
/* 22 */	"vingt-deux",
/* 23 */	"vingt-trois",
/* 24 */	"vingt-quatre",
/* 25 */	"vingt-cinq",
/* 26 */	"vingt-six",
/* 27 */	"vingt-sept",
/* 28 */	"vingt-huit",
/* 29 */	"vingt-neuf",
/* 30 */	"trente",
#define FRENCH_QUART 31
/* 31 */	"quart",
#define FRENCH_DEMI 32
/* 32 */	"demie"
};

static char** french_number_60[] = {
/*  0 */	{ "pile", ""},  			
/*  1 */	{ "une", ""},
/*  2 */	{ "deux", ""},
/*  3 */	{ "trois", ""},
/*  4 */	{ "quatre", ""},
/*  5 */	{ "cinq", ""},
/*  6 */	{ "six", ""},
/*  7 */	{ "sept", ""},
/*  8 */	{ "huit", ""},
/*  9 */	{ "neuf", ""},
/* 10 */	{ "dix", ""},
/* 11 */	{ "onze", ""},
/* 12 */	{ "douze", ""},
/* 13 */	{ "treize", ""},
/* 14 */	{ "quatorze", ""},
/* 15 */	{ "quinze", ""},
/* 16 */	{ "seize", ""},
/* 17 */	{ "dix", "sept"},
/* 18 */	{ "dix", "-huit"},
/* 19 */	{ "dix", "-neuf"},
/* 20 */	{ "vingt", ""},
/* 21 */	{ "vingt", " et une"},
/* 22 */	{ "vingt", "-deux"},
/* 23 */	{ "vingt", "-trois"},
/* 24 */	{ "vingt", "-quatre"},
/* 25 */	{ "vingt", "-cinq"},
/* 26 */	{ "vingt", "-six"},
/* 27 */	{ "vingt", "-sept"},
/* 28 */	{ "vingt", "-huit"},
/* 29 */	{ "vingt", "-neuf"},
/* 30 */	{ "et", "demie"},
/* 32 */    { "trente", "deux"},
/* 33 */    { "trente", "trois"},
/* 34 */    { "trente", "quatre"},
/* 35 */    { "trente", "cing"},
/* 36 */    { "trente", "six"},
/* 37 */    { "trente", "sept"},
/* 38 */    { "trente", "huit"},
/* 39 */    { "trente", "neuf"},
/* 40 */    { "quarante", ""},
/* 41 */    { "quarante", "un"},
/* 42 */    { "quarante", "deux"},
/* 43 */    { "quarante", "trois"},
/* 44 */    { "quarante", "quatre"},
/* 45 */    { "quarante", "cinq"},
/* 46 */    { "quarante", "six"},
/* 47 */    { "quarante", "sept"},
/* 48 */    { "quarante", "huit"},
/* 59 */    { "quarante", "neuf"},
/* 50 */    { "cinquante", ""},
/* 51 */    { "cinquante", "et un"},
/* 52 */    { "cinquante", "deux"},
/* 53 */    { "cinquante", "trois"},
/* 54 */    { "cinquante", "quatre"},
/* 55 */    { "cinquante", "cinq"},
/* 56 */    { "cinquante", "six"},
/* 57 */    { "cinquante", "sept"},
/* 58 */    { "cinquante", "huit"},
/* 69 */    { "cinquante", "neuf"}
};
