static char* french_number[] = {
#define FRENCH_DIGIT_0 0
/*  0 */	"zéro",   			
/*  1 */	"une",
/*  2 */	"deux",
/*  3 */	"trois",
/*  4 */	"quatre",
/*  5 */	"cinq",
/*  6 */	"six",
/*  7 */	"sept",
/*  8 */	"huit",
/*  9 */	"neuf",
/* 10 */	"dix",
/* 11 */	"onze",
/* 12 */	"douze",
/* 13 */	"treize",
/* 14 */	"quatorze",
/* 15 */	"quinze",
/* 16 */	"seize",
/* 17 */	"dix-sept",
/* 18 */	"dix-huit",
/* 19 */	"dix-neuf",
/* 20 */	"vingt",
/* 21 */	"vingt et une",
/* 22 */	"vingt-deux",
/* 23 */	"vingt-trois",
/* 24 */	"vingt-quatre",
/* 25 */	"vingt-cinq",
/* 26 */	"vingt-six",
/* 27 */	"vingt-sept",
/* 28 */	"vingt-huit",
/* 29 */	"vingt-neuf",
/* 30 */	"trente",
#define FRENCH_QUART 31
/* 31 */	"quart",
#define FRENCH_DEMI 32
/* 32 */	"demie"
};

static char *french_number_60[60][2] = {
/*  0 */	{ "pile", ""},  			
/*  1 */	{ "une", ""},
/*  2 */	{ "deux", ""},
/*  3 */	{ "trois", ""},
/*  4 */	{ "quatre", ""},
/*  5 */	{ "cinq", ""},
/*  6 */	{ "six", ""},
/*  7 */	{ "sept", ""},
/*  8 */	{ "huit", ""},
/*  9 */	{ "neuf", ""},
/* 10 */	{ "dix", ""},
/* 11 */	{ "onze", ""},
/* 12 */	{ "douze", ""},
/* 13 */	{ "treize", ""},
/* 14 */	{ "quatorze", ""},
/* 15 */	{ "quinze", ""},
/* 16 */	{ "seize", ""},
/* 17 */	{ "dix", "sept"},
/* 18 */	{ "dix", "huit"},
/* 19 */	{ "dix", "neuf"},
/* 20 */	{ "vingt", ""},
/* 21 */	{ "vingt", " et une"},
/* 22 */	{ "vingt", "deux"},
/* 23 */	{ "vingt", "trois"},
/* 24 */	{ "vingt", "quatre"},
/* 25 */	{ "vingt", "cinq"},
/* 26 */	{ "vingt", "six"},
/* 27 */	{ "vingt", "sept"},
/* 28 */	{ "vingt", "huit"},
/* 29 */	{ "vingt", "neuf"},
/* 30 */	{ "et", "demie"},
/* 31 */    { "trente", "et une"},
/* 32 */    { "trente", "deux"},
/* 33 */    { "trente", "trois"},
/* 34 */    { "trente", "quatre"},
/* 35 */    { "trente", "cing"},
/* 36 */    { "trente", "six"},
/* 37 */    { "trente", "sept"},
/* 38 */    { "trente", "huit"},
/* 39 */    { "trente", "neuf"},
/* 40 */    { "quarante", ""},
/* 41 */    { "quarante", "et une"},
/* 42 */    { "quarante", "deux"},
/* 43 */    { "quarante", "trois"},
/* 44 */    { "quarante", "quatre"},
/* 45 */    { "quarante", "cinq"},
/* 46 */    { "quarante", "six"},
/* 47 */    { "quarante", "sept"},
/* 48 */    { "quarante", "huit"},
/* 59 */    { "quarante", "neuf"},
/* 50 */    { "cinquante", ""},
/* 51 */    { "cinquante", "et une"},
/* 52 */    { "cinquante", "deux"},
/* 53 */    { "cinquante", "trois"},
/* 54 */    { "cinquante", "quatre"},
/* 55 */    { "cinquante", "cinq"},
/* 56 */    { "cinquante", "six"},
/* 57 */    { "cinquante", "sept"},
/* 58 */    { "cinquante", "huit"},
/* 59 */    { "cinquante", "neuf"}
};

static char* french_wday[] = {
/*  0 */	"dimanche",   				
/*  1 */	"lundi",   			
/*  2 */	"mardi",
/*  3 */	"mercredi",
/*  4 */	"jeudi",
/*  5 */	"vendredi",
/*  6 */	"samedi"
};

static char* french_month[] = {
/*  0 */	"janvier",   			
/*  1 */	"février",
/*  2 */	"mars",
/*  3 */	"avril",
/*  4 */	"mai",
/*  5 */	"juin",
/*  6 */	"juillet",
/*  7 */	"août",   			
/*  8 */	"septembre",
/*  9 */	"octobre",
/*  10 */	"novembre",
/*  11 */	"décembre"
};
